
# A string used as a namespace for the functions.
project_id = "fhmvdprcmhkolyzuecrr"

[functions.get-public-analysis]
verify_jwt = false
insert_mode = "upsert"

[functions.analyze-responses]
verify_jwt = false
insert_mode = "upsert"

[functions.generate-activity] 
verify_jwt = true
insert_mode = "upsert"

[functions.get-comprehensive-analysis]
verify_jwt = false
insert_mode = "upsert"
