
project_id = "fhmvdprcmhkolyzuecrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true
port = 54327

[vector]
enabled = true

[edge_functions]
[edge_functions.analyze-concise-responses]
verify_jwt = true

[edge_functions.serve]
verify_jwt = true
