
project_id = "fhmvdprcmhkolyzuecrr"
[functions.analyze-concise-responses]
verify_jwt = true
timeout_seconds = 120
[functions.analyze-responses]
verify_jwt = true
[functions.generate-activity]
verify_jwt = true
[functions.get-public-analysis]
verify_jwt = false
[functions.delete-concise-analysis]
verify_jwt = true
