
project_id = "fhmvdprcmhkolyzuecrr"
[functions.analyze-concise-responses]
verify_jwt = true
[functions.analyze-responses]
verify_jwt = true
[functions.generate-activity]
verify_jwt = true
[functions.get-public-analysis]
verify_jwt = false
[functions.delete-concise-analysis]
verify_jwt = true
[functions.create-assessment-payment]
verify_jwt = true
[functions.verify-assessment-payment]
verify_jwt = true
[functions.grant-bonus-credits]
verify_jwt = true
