
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

# Enable the Functions docker image
# This doesn't affect Edge Functions, which always use the Edge Runtime
[functions.serve]
enabled = true
port = 54324
