
project_id = "fhmvdprcmhkolyzuecrr"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-comprehensive-responses]
verify_jwt = false
insert_mode = "upsert"

[functions.get-public-analysis]
verify_jwt = false
insert_mode = "upsert"

[functions.analyze-responses]
verify_jwt = false
insert_mode = "upsert"

[functions.generate-activity] 
verify_jwt = true
insert_mode = "upsert"

[functions.get-comprehensive-analysis]
verify_jwt = false
insert_mode = "upsert"
